# Generated by Django 5.1.5 on 2025-08-06 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='link',
            field=models.CharField(default='https://www.facebook.com/KoloFantastykiIGier/', max_length=500),
        ),
    ]
