# Generated by Django 5.1.5 on 2025-08-15 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketDownloadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
