# Generated by Django 5.1.5 on 2025-08-15 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_ticketdownloadlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='email',
        ),
    ]
