# Generated by Django 5.2.17 on 2026-09-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_ticket_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='counter',
            name='link',
            field=models.URLField(default='https://www.facebook.com/KoloFantastykiIGier/', max_length=500),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_id',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AddIndex(
            model_name='ticketdownloadlog',
            index=models.Index(fields=['ip_address', 'created_at'], name='ticket_ip_created_idx'),
        ),
        migrations.AddIndex(
            model_name='contactattempt',
            index=models.Index(fields=['ip_address', 'created_at'], name='contact_ip_created_idx'),
        ),
    ]
